# Select current database type:
# mysql, sqlite
database: sqlite

mysql:
  host: ""
  basename: ""
  port: ""
  username: ""
  password: ""

purge:
  # Should we use this feature
  enable: true

  # How long before we have to reconcile the data in minutes
  task-repeat-delay: 300

  # How many days should the player's data not be updated to delete him from the database
  max-none-activity-days: 90

xp-system:
  # Should we reset player experience level after level up
  reset: false

  # How much experience we should add for next level
  step: 1000